services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network
  wrk-benchmark:
    build:
      context: ./benchmarking
      dockerfile: Dockerfile
   
  backend1:
    build:
      context: ./backend
    networks:
      - app-network

  backend2:
    build:
      context: ./backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
